# Generated by Django 6.0 on 2026-01-17 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUploadJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(choices=[('students', 'Students'), ('CIS', 'CIS'), ('marks', 'Marks'), ('target', 'Target')], max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.IntegerField(blank=True, null=True)),
                ('success_rows', models.IntegerField(blank=True, null=True)),
                ('failed_rows', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by', on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'verbose_name': 'Bulk Upload Job',
                'verbose_name_plural': 'Bulk Upload Jobs',
                'db_table': 'bulk_upload_job',
            },
        ),
    ]
