# Generated by Django 4.2.11 on 2026-04-14 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulk_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkuploadjob',
            name='uploaded_by',
            field=models.ForeignKey(db_column='uploaded_by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
