# Generated by Django 4.2.11 on 2026-04-14 11:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StressCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Academic / Emotional / Lifestyle', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'stress_category',
            },
        ),
        migrations.CreateModel(
            name='StressMaster',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Survey title', max_length=255)),
                ('month', models.IntegerField(help_text='1-12', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField()),
                ('is_active', models.BooleanField(default=False, help_text='Only one survey active at a time')),
                ('end_date', models.DateTimeField(blank=True, help_text='Deadline for survey submission', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stress_survey',
            },
        ),
        migrations.CreateModel(
            name='StressQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField(unique=True)),
                ('is_reverse', models.BooleanField(default=False, help_text='If true, high score (4) is positive. If false, high score indicates stress.')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='stress.stresscategory')),
            ],
            options={
                'db_table': 'stress_question',
            },
        ),
        migrations.CreateModel(
            name='StressQuestionSet',
            fields=[
                ('question_set_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stress_question_set',
            },
        ),
        migrations.CreateModel(
            name='SurveySessionToken',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='Unique anonymous token', max_length=255, unique=True)),
                ('is_used', models.BooleanField(default=False, help_text='Prevents duplicate submission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='stress.stressmaster')),
            ],
            options={
                'db_table': 'stress_session_token',
            },
        ),
        migrations.CreateModel(
            name='StressSubmission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stress_submissions', to='academics.batch')),
                ('survey', models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='stress.stressmaster')),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='stress.surveysessiontoken')),
            ],
            options={
                'db_table': 'stress_submission',
            },
        ),
        migrations.AddField(
            model_name='stressmaster',
            name='approved_question_set',
            field=models.ForeignKey(db_column='question_set_id', on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to='stress.stressquestionset'),
        ),
        migrations.CreateModel(
            name='StressQuestionSetQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.PROTECT, related_name='question_sets', to='stress.stressquestion')),
                ('question_set', models.ForeignKey(db_column='question_set_id', on_delete=django.db.models.deletion.CASCADE, related_name='set_questions', to='stress.stressquestionset')),
            ],
            options={
                'db_table': 'stress_question_set_question',
                'unique_together': {('question_set', 'question')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='stressmaster',
            unique_together={('month', 'year')},
        ),
        migrations.CreateModel(
            name='StressAnswer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('response_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.PROTECT, to='stress.stressquestion')),
                ('submission', models.ForeignKey(db_column='submission_id', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='stress.stresssubmission')),
            ],
            options={
                'db_table': 'stress_answer',
                'unique_together': {('submission', 'question')},
            },
        ),
        migrations.CreateModel(
            name='StressActionPlan',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('analysis_remarks', models.TextField(help_text="HOD's analysis of the stress data")),
                ('action_taken', models.TextField(help_text='Steps taken to address high stress')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stress_action_plans', to='academics.batch')),
                ('survey', models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='stress.stressmaster')),
            ],
            options={
                'db_table': 'stress_action_plan',
                'unique_together': {('survey', 'batch')},
            },
        ),
    ]
