# Generated by Django 6.0 on 2025-12-31 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StressCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='academic/emotional/lifestyle', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StressSurvey',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='survey title', max_length=255)),
                ('month', models.IntegerField(help_text='1/12')),
                ('year', models.IntegerField()),
                ('is_active', models.BooleanField(default=False, help_text='only one survey active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StressQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField(help_text='The actual question text')),
                ('is_active', models.BooleanField(default=True, help_text='Enables/disables question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='stress.stresscategory')),
                ('survey_id', models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='stress.stresssurvey')),
            ],
        ),
        migrations.CreateModel(
            name='StressResponse',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='Anonymous session token', max_length=255)),
                ('response_value', models.IntegerField(help_text='Scale 0-4')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_id', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='stress.stressquestion')),
                ('survey_id', models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='stress.stresssurvey')),
            ],
        ),
        migrations.CreateModel(
            name='SurveySessionToken',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='Unique anonymous token', max_length=255, unique=True)),
                ('is_used', models.BooleanField(default=False, help_text='Prevents duplicate submission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey_id', models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, to='stress.stresssurvey')),
            ],
        ),
    ]
