# Generated by Django 6.0 on 2026-01-14 11:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stresscategory',
            name='name',
            field=models.CharField(help_text='academic/emotional/lifestyle', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='stressquestion',
            name='category_id',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='stress.stresscategory'),
        ),
        migrations.AlterField(
            model_name='stressquestion',
            name='survey_id',
            field=models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='stress.stresssurvey'),
        ),
        migrations.AlterField(
            model_name='stressresponse',
            name='question_id',
            field=models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='stress.stressquestion'),
        ),
        migrations.AlterField(
            model_name='stressresponse',
            name='response_value',
            field=models.IntegerField(help_text='Scale 0-4', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='stressresponse',
            name='survey_id',
            field=models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='stress.stresssurvey'),
        ),
        migrations.AlterField(
            model_name='stressresponse',
            name='token',
            field=models.ForeignKey(db_column='token_id', on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='stress.surveysessiontoken'),
        ),
        migrations.AlterField(
            model_name='stresssurvey',
            name='month',
            field=models.IntegerField(help_text='1-12', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='surveysessiontoken',
            name='survey_id',
            field=models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='stress.stresssurvey'),
        ),
        migrations.AlterUniqueTogether(
            name='stressquestion',
            unique_together={('survey_id', 'question_text')},
        ),
        migrations.AlterUniqueTogether(
            name='stressresponse',
            unique_together={('token', 'question_id')},
        ),
        migrations.AlterUniqueTogether(
            name='stresssurvey',
            unique_together={('month', 'year')},
        ),
    ]
