# Generated by Django 6.0 on 2026-02-21 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(help_text='Academic Year', max_length=20)),
                ('report_file', models.FileField(help_text='PDF Report', upload_to='reports/')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', help_text='draft/approved/rejected', max_length=20)),
                ('auditor_remark', models.TextField(blank=True, help_text='Auditor comments', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='academics.course')),
            ],
        ),
    ]
