# Generated by Django 6.0 on 2026-03-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='JSON representation of the unified grid', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DACReport',
            fields=[
                ('dac_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(help_text='Academic Year (e.g., 2025 - 26)', max_length=20)),
                ('class_name', models.CharField(blank=True, help_text='e.g., FY, SY, TY, Final Year', max_length=15, null=True)),
                ('semester', models.CharField(blank=True, help_text='e.g., 1, 2, 3...', max_length=5, null=True)),
                ('file', models.FileField(help_text='DAC Report file (PDF or Excel)', upload_to='dac_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', help_text='Pending/Approved/Rejected/Verified', max_length=20)),
                ('auditor_remark', models.TextField(blank=True, help_text='Rejection reason or auditor comments', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('Direct', 'Direct Attainment'), ('Indirect', 'Indirect Attainment'), ('Batch', 'Batch evaluation (PO/PSO)')], default='Direct', max_length=20)),
                ('year', models.CharField(help_text='Academic Year', max_length=20)),
                ('report_file', models.FileField(help_text='PDF Report', upload_to='reports/')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Verified', 'Verified')], default='Draft', help_text='draft/approved/rejected', max_length=20)),
                ('auditor_remark', models.TextField(blank=True, help_text='Auditor comments', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
