# Generated by Django 6.0 on 2026-03-08 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorboard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remarks_board', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dacreport',
            name='batch_id',
            field=models.ForeignKey(blank=True, db_column='batch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dac_reports', to='academics.batch'),
        ),
        migrations.AddField(
            model_name='dacreport',
            name='program_id',
            field=models.ForeignKey(db_column='program_id', on_delete=django.db.models.deletion.PROTECT, related_name='dac_reports', to='academics.program'),
        ),
        migrations.AddField(
            model_name='dacreport',
            name='uploaded_by',
            field=models.ForeignKey(db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_dac_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='batch_id',
            field=models.ForeignKey(blank=True, db_column='batch_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='academics.batch'),
        ),
        migrations.AddField(
            model_name='report',
            name='course_id',
            field=models.ForeignKey(blank=True, db_column='course_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='academics.course'),
        ),
        migrations.AddField(
            model_name='report',
            name='program_id',
            field=models.ForeignKey(blank=True, db_column='program_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='academics.program'),
        ),
        migrations.AddField(
            model_name='report',
            name='user_id_approved',
            field=models.ForeignKey(blank=True, db_column='approved_by', help_text='Coordinator/HOD', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='user_id_created',
            field=models.ForeignKey(db_column='created_by', help_text='Author', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
