# Generated by Django 4.2.11 on 2026-04-14 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='user_id_approved',
            field=models.ForeignKey(blank=True, db_column='approved_by', help_text='Coordinator/HOD', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='user_id_created',
            field=models.ForeignKey(db_column='created_by', help_text='Author', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dacreport',
            name='batch_id',
            field=models.ForeignKey(blank=True, db_column='batch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dac_reports', to='academics.batch'),
        ),
        migrations.AddField(
            model_name='dacreport',
            name='program_id',
            field=models.ForeignKey(db_column='program_id', on_delete=django.db.models.deletion.PROTECT, related_name='dac_reports', to='academics.program'),
        ),
        migrations.AddField(
            model_name='dacreport',
            name='uploaded_by',
            field=models.ForeignKey(db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_dac_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditorboard',
            name='audit_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='reports.auditperiod'),
        ),
        migrations.AddField(
            model_name='auditorboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='auditorboard',
            unique_together={('user', 'audit_period')},
        ),
    ]
