# Generated by Django 6.0 on 2026-02-26 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_academicsetup_curriculum_link'),
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='batch_id',
            field=models.ForeignKey(blank=True, db_column='batch_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='academics.batch'),
        ),
        migrations.AddField(
            model_name='report',
            name='program_id',
            field=models.ForeignKey(blank=True, db_column='program_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='academics.program'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('Direct', 'Direct Attainment'), ('Indirect', 'Indirect Attainment'), ('Batch', 'Batch evaluation (PO/PSO)')], default='Direct', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='course_id',
            field=models.ForeignKey(blank=True, db_column='course_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='academics.course'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Verified', 'Verified')], default='Draft', help_text='draft/approved/rejected', max_length=20),
        ),
    ]
