# Generated by Django 6.0 on 2026-03-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dacreport',
            name='auditor_remark',
            field=models.TextField(blank=True, help_text='Rejection reason or auditor comments', null=True),
        ),
        migrations.AddField(
            model_name='dacreport',
            name='status',
            field=models.CharField(default='Pending', help_text='Pending/Approved/Rejected/Verified', max_length=20),
        ),
    ]
