# Generated by Django 6.0 on 2026-02-26 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_academicsetup_curriculum_link'),
        ('reports', '0003_report_batch_id_report_program_id_report_report_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DACReport',
            fields=[
                ('dac_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(help_text='Academic Year (e.g., 2025 - 26)', max_length=20)),
                ('class_name', models.CharField(blank=True, help_text='e.g., FY, SY, TY, Final Year', max_length=15, null=True)),
                ('semester', models.CharField(blank=True, help_text='e.g., 1, 2, 3...', max_length=5, null=True)),
                ('file', models.FileField(help_text='DAC Report file (PDF or Excel)', upload_to='dac_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('batch_id', models.ForeignKey(blank=True, db_column='batch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dac_reports', to='academics.batch')),
                ('program_id', models.ForeignKey(db_column='program_id', on_delete=django.db.models.deletion.PROTECT, related_name='dac_reports', to='academics.program')),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_dac_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
