# Generated by Django 4.2.11 on 2026-04-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('DANGER', 'Alert/Danger')], default='INFO', max_length=10)),
                ('module', models.CharField(choices=[('ATR', 'ATR Module'), ('COURSE', 'Course Management'), ('REPORT', 'Report Approval'), ('SURVEY', 'Survey Module'), ('STRESS', 'Stress Analysis'), ('AUDIT', 'Audit Module'), ('GENERAL', 'General System')], default='GENERAL', max_length=20)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('IMPORTANT', 'Important'), ('NORMAL', 'Normal')], default='NORMAL', max_length=15)),
                ('action_link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
