# Generated by Django 6.0 on 2026-02-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='module',
            field=models.CharField(choices=[('ATR', 'ATR Module'), ('COURSE', 'Course Management'), ('REPORT', 'Report Approval'), ('SURVEY', 'Survey Module'), ('STRESS', 'Stress Analysis'), ('AUDIT', 'Audit Module'), ('GENERAL', 'General System')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('IMPORTANT', 'Important'), ('NORMAL', 'Normal')], default='NORMAL', max_length=15),
        ),
    ]
