# Generated by Django 6.0 on 2025-12-31 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_name', models.CharField(max_length=100)),
                ('assessment_type', models.CharField(choices=[('CIS', 'CIS'), ('SAR', 'SAR'), ('OTHER', 'OTHER')], max_length=20)),
                ('max_marks', models.IntegerField()),
                ('weightage', models.FloatField()),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentCOMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('co_weightage', models.FloatField()),
                ('assessment_id', models.ForeignKey(db_column='assessment_id', on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment')),
                ('co_id', models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.CASCADE, to='academics.co')),
            ],
        ),
        migrations.CreateModel(
            name='MarksEntry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('marks_obtained', models.FloatField()),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_id', models.ForeignKey(db_column='assessment_id', on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment')),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
        ),
    ]
