# Generated by Django 6.0.1 on 2026-01-11 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_name', models.CharField(max_length=100)),
                ('assessment_type', models.CharField(max_length=50)),
                ('max_marks', models.IntegerField()),
                ('weightage', models.FloatField()),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.IntegerField()),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='assessments/evidence/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, to='academics.course')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'db_table': 'assessments_assessment',
            },
        ),
        migrations.CreateModel(
            name='AssessmentCOMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('co_weightage', models.FloatField()),
                ('assessment_id', models.ForeignKey(db_column='assessment_id', on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment')),
                ('co_id', models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.PROTECT, to='academics.co')),
            ],
            options={
                'db_table': 'assessments_assessment_co_mapping',
            },
        ),
        migrations.CreateModel(
            name='MarksEntry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('marks_obtained', models.FloatField()),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_id', models.ForeignKey(db_column='assessment_id', on_delete=django.db.models.deletion.PROTECT, to='assessments.assessment')),
                ('entered_by', models.ForeignKey(db_column='entered_by', on_delete=django.db.models.deletion.PROTECT, to='users.user')),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.PROTECT, to='users.student')),
            ],
            options={
                'db_table': 'assessments_marks_entry',
            },
        ),
    ]
