# Generated by Django 6.0 on 2025-12-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('CIS', 'CIS'), ('SAR', 'SAR'), ('OTHER', 'OTHER')], max_length=20),
        ),
    ]
