# Generated by Django 6.0 on 2026-03-08 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseIndirectAttainment',
            fields=[
                ('attainment_id', models.AutoField(primary_key=True, serialize=False)),
                ('attainment_value', models.FloatField()),
                ('academic_year', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'indirect_attainment_course',
            },
        ),
        migrations.CreateModel(
            name='ActivityIndirectAttainment',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('Co-curricular', 'Co-curricular'), ('Industrial Visit', 'Industrial Visit'), ('Extra-curricular', 'Extra-curricular')], max_length=50)),
                ('score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('co_id', models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.PROTECT, to='academics.co')),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, to='academics.course')),
            ],
            options={
                'db_table': 'indirect_attainment_activity',
            },
        ),
    ]
