# Generated by Django 6.0 on 2026-01-14 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_batch_unique_together_and_more'),
        ('indirect_attainment', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indirectattainment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='indirectattainment',
            name='co_id',
            field=models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.PROTECT, to='academics.co'),
        ),
        migrations.AlterField(
            model_name='indirectattainment',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, to='academics.course'),
        ),
        migrations.AlterField(
            model_name='indirectattainment',
            name='student_id',
            field=models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.student'),
        ),
        migrations.AlterUniqueTogether(
            name='indirectattainment',
            unique_together={('course_id', 'co_id', 'student_id', 'activity_type')},
        ),
        migrations.AlterModelTable(
            name='indirectattainment',
            table='indirect_attainment',
        ),
    ]
