# Generated by Django 6.0 on 2026-02-21 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indirect_attainment', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indirectattainment',
            name='student_id',
            field=models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.student'),
        ),
        migrations.AlterUniqueTogether(
            name='indirectattainment',
            unique_together={('course_id', 'co_id', 'student_id', 'activity_type')},
        ),
    ]
