# Generated by Django 4.2.11 on 2026-04-14 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indirect_attainment', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityindirectattainment',
            name='student_id',
            field=models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.student'),
        ),
        migrations.AlterUniqueTogether(
            name='courseindirectattainment',
            unique_together={('course_id', 'co_id', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='activityindirectattainment',
            unique_together={('course_id', 'co_id', 'student_id', 'activity_type')},
        ),
    ]
