# Generated by Django 6.0 on 2026-02-27 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('indirect_attainment', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityindirectattainment',
            name='student_id',
            field=models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.student'),
        ),
        migrations.AddField(
            model_name='courseindirectattainment',
            name='co_id',
            field=models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.PROTECT, to='academics.co'),
        ),
        migrations.AddField(
            model_name='courseindirectattainment',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, to='academics.course'),
        ),
        migrations.AlterUniqueTogether(
            name='activityindirectattainment',
            unique_together={('course_id', 'co_id', 'student_id', 'activity_type')},
        ),
        migrations.AlterUniqueTogether(
            name='courseindirectattainment',
            unique_together={('course_id', 'co_id', 'academic_year')},
        ),
    ]
