# Generated by Django 6.0 on 2026-03-08 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentCOMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('co_weightage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CisEvidence',
            fields=[
                ('evidence_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.IntegerField()),
                ('assessment_tool', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='cis_evidence/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarksEntry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('marks_obtained', models.FloatField()),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_name', models.CharField(max_length=100)),
                ('assessment_type', models.CharField(choices=[('SA_TH', 'Summative Theory'), ('FA_TH', 'Formative Theory'), ('SA_PR', 'Summative Practical'), ('FA_PR', 'Formative Practical'), ('SLA', 'Self Learning Assessment'), ('CES', 'Course Exit Survey')], max_length=20)),
                ('max_marks', models.IntegerField()),
                ('weightage', models.FloatField()),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.IntegerField()),
                ('configuration', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, to='academics.course')),
            ],
        ),
    ]
