# Generated by Django 4.2.11 on 2026-04-14 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksentry',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.PROTECT, to='users.student'),
        ),
        migrations.AddField(
            model_name='marksentry',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cisevidence',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, to='academics.course'),
        ),
        migrations.AddField(
            model_name='cisevidence',
            name='uploaded_by',
            field=models.ForeignKey(db_column='uploaded_by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentcomapping',
            name='assessment_id',
            field=models.ForeignKey(db_column='assessment_id', on_delete=django.db.models.deletion.PROTECT, to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='assessmentcomapping',
            name='co_id',
            field=models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.PROTECT, to='academics.co'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, to='academics.course'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='marksentry',
            unique_together={('assessment_id', 'student_id')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmentcomapping',
            unique_together={('assessment_id', 'co_id')},
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('course_id', 'assessment_name', 'academic_year', 'semester')},
        ),
    ]
