# Generated by Django 6.0 on 2026-01-11 11:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_batch_unique_together_and_more'),
        ('assessments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assessmentcomapping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('SA_TH', 'Summative Theory'), ('FA_TH', 'Formative Theory'), ('SA_PR', 'Summative Practical'), ('FA_PR', 'Formative Practical'), ('SLA', 'Self Learning Assessment'), ('CES', 'Course Exit Survey')], max_length=20),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, to='academics.course'),
        ),
        migrations.AlterField(
            model_name='assessmentcomapping',
            name='assessment_id',
            field=models.ForeignKey(db_column='assessment_id', on_delete=django.db.models.deletion.PROTECT, to='assessments.assessment'),
        ),
        migrations.AlterField(
            model_name='assessmentcomapping',
            name='co_id',
            field=models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.PROTECT, to='academics.co'),
        ),
        migrations.AlterField(
            model_name='marksentry',
            name='assessment_id',
            field=models.ForeignKey(db_column='assessment_id', on_delete=django.db.models.deletion.PROTECT, to='assessments.assessment'),
        ),
        migrations.AlterField(
            model_name='marksentry',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.PROTECT, to='users.student'),
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('course_id', 'assessment_name', 'academic_year', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmentcomapping',
            unique_together={('assessment_id', 'co_id')},
        ),
        migrations.AlterUniqueTogether(
            name='marksentry',
            unique_together={('assessment_id', 'student_id')},
        ),
    ]
