# Generated by Django 6.0 on 2026-02-27 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='Example: 2025 - 26', max_length=15)),
                ('semester_type', models.CharField(choices=[('Odd', 'Odd'), ('Even', 'Even')], max_length=10)),
                ('curriculum_link', models.URLField(default='https://econtent.msbte.edu.in/curriculum_search/', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_year', models.IntegerField(help_text='Year of admission (start)')),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.CreateModel(
            name='CO',
            fields=[
                ('co_id', models.AutoField(primary_key=True, serialize=False)),
                ('co_number', models.CharField(help_text='co1/co2/co3 etc', max_length=20)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Outcome',
                'verbose_name_plural': 'Course Outcomes',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('course_title', models.CharField(blank=True, max_length=200, null=True)),
                ('course_abbr', models.CharField(blank=True, max_length=50, null=True)),
                ('class_year', models.CharField(blank=True, max_length=20, null=True)),
                ('assessment_tools', models.JSONField(blank=True, default=dict, null=True)),
                ('is_internal', models.BooleanField(default=True)),
                ('co_status', models.CharField(default='PENDING', max_length=20)),
                ('mapping_status', models.CharField(default='PENDING', max_length=20)),
                ('course_atr', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PEO',
            fields=[
                ('peo_id', models.AutoField(primary_key=True, serialize=False)),
                ('peo_number', models.CharField(help_text='PEO 1, PEO 2 etc.', max_length=20)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program Educational Objective',
                'verbose_name_plural': 'Program Educational Objectives',
                'db_table': 'academics_peo',
            },
        ),
        migrations.CreateModel(
            name='PO',
            fields=[
                ('po_id', models.AutoField(primary_key=True, serialize=False)),
                ('po_number', models.CharField(help_text='po1/po2/po3 etc', max_length=20)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program Outcome',
                'verbose_name_plural': 'Program Outcomes',
            },
        ),
        migrations.CreateModel(
            name='POTarget',
            fields=[
                ('target_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=9)),
                ('target_value', models.FloatField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'academics_po_target',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=100)),
                ('duration', models.IntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramStatement',
            fields=[
                ('statement_id', models.AutoField(primary_key=True, serialize=False)),
                ('statement_type', models.CharField(choices=[('INSTITUTE_VISION', 'Institute Vision'), ('INSTITUTE_MISSION', 'Institute Mission'), ('DEPT_VISION', 'Department Vision'), ('DEPT_MISSION', 'Department Mission')], max_length=50)),
                ('statement_number', models.CharField(blank=True, help_text='M1, M2 etc.', max_length=10, null=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program Statement',
                'verbose_name_plural': 'Program Statements',
                'db_table': 'academics_program_statement',
            },
        ),
        migrations.CreateModel(
            name='PSO',
            fields=[
                ('pso_id', models.AutoField(primary_key=True, serialize=False)),
                ('pso_number', models.CharField(help_text='pso1/pso2', max_length=20)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program Specific Outcome',
                'verbose_name_plural': 'Program Specific Outcomes',
            },
        ),
        migrations.CreateModel(
            name='PSOTarget',
            fields=[
                ('target_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=9)),
                ('target_value', models.FloatField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'academics_pso_target',
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('scheme_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheme_name', models.CharField(max_length=100)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='COPOMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('weightage', models.IntegerField(blank=True, help_text='mapping weight 1/2/3', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('co_id', models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.PROTECT, related_name='po_mappings', to='academics.co')),
            ],
        ),
        migrations.CreateModel(
            name='COPSOMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('weightage', models.IntegerField(blank=True, help_text='mapping weight 1/2/3', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('co_id', models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.PROTECT, related_name='pso_mappings', to='academics.co')),
            ],
        ),
        migrations.CreateModel(
            name='COTarget',
            fields=[
                ('target_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=9)),
                ('target_value', models.FloatField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('co_id', models.ForeignKey(blank=True, db_column='co_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.co')),
            ],
            options={
                'db_table': 'academics_co_target',
            },
        ),
    ]
