# Generated by Django 6.0 on 2026-01-17 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CO',
            fields=[
                ('co_id', models.AutoField(primary_key=True, serialize=False)),
                ('co_number', models.CharField(help_text='co1/co2/co3 etc', max_length=20)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Outcome',
                'verbose_name_plural': 'Course Outcomes',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=100)),
                ('duration', models.IntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('scheme_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheme_name', models.CharField(max_length=100)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='COTarget',
            fields=[
                ('target_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=9)),
                ('target_value', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('co_id', models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.PROTECT, to='academics.co')),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, to='academics.course')),
            ],
            options={
                'db_table': 'academics_co_target',
            },
        ),
        migrations.AddField(
            model_name='co',
            name='course_id',
            field=models.ForeignKey(db_column='c_id', on_delete=django.db.models.deletion.PROTECT, related_name='cos', to='academics.course'),
        ),
        migrations.CreateModel(
            name='PO',
            fields=[
                ('po_id', models.AutoField(primary_key=True, serialize=False)),
                ('po_number', models.CharField(help_text='po1/po2/po3 etc', max_length=20)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program_id', models.ForeignKey(blank=True, db_column='p_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos', to='academics.program')),
            ],
            options={
                'verbose_name': 'Program Outcome',
                'verbose_name_plural': 'Program Outcomes',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='program_id',
            field=models.ForeignKey(db_column='p_id', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.program'),
        ),
        migrations.CreateModel(
            name='PSO',
            fields=[
                ('pso_id', models.AutoField(primary_key=True, serialize=False)),
                ('pso_number', models.CharField(help_text='pso1/pso2', max_length=20)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program_id', models.ForeignKey(db_column='p_id', on_delete=django.db.models.deletion.PROTECT, related_name='psos', to='academics.program')),
            ],
            options={
                'verbose_name': 'Program Specific Outcome',
                'verbose_name_plural': 'Program Specific Outcomes',
                'unique_together': {('program_id', 'pso_number')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='scheme_id',
            field=models.ForeignKey(blank=True, db_column='scheme_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.scheme'),
        ),
        migrations.AlterUniqueTogether(
            name='co',
            unique_together={('course_id', 'co_number')},
        ),
        migrations.CreateModel(
            name='COPOMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('weightage', models.IntegerField(blank=True, help_text='mapping weight 1/2/3', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('co_id', models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.PROTECT, related_name='po_mappings', to='academics.co')),
                ('po_id', models.ForeignKey(db_column='po_id', on_delete=django.db.models.deletion.PROTECT, related_name='co_mappings', to='academics.po')),
            ],
            options={
                'unique_together': {('co_id', 'po_id')},
            },
        ),
        migrations.CreateModel(
            name='COPSOMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('weightage', models.IntegerField(blank=True, help_text='mapping weight 1/2/3', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('co_id', models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.PROTECT, related_name='pso_mappings', to='academics.co')),
                ('pso_id', models.ForeignKey(db_column='pso_id', on_delete=django.db.models.deletion.PROTECT, related_name='co_mappings', to='academics.pso')),
            ],
            options={
                'unique_together': {('co_id', 'pso_id')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_code', 'program_id')},
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_year', models.IntegerField(help_text='Year of admission')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program_id', models.ForeignKey(db_column='p_id', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='academics.program')),
                ('scheme_id', models.ForeignKey(db_column='scheme_id', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='academics.scheme')),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'unique_together': {('program_id', 'batch_year')},
            },
        ),
    ]
