# Generated by Django 6.0 on 2026-01-10 19:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='COTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='co',
            unique_together={('course_id', 'co_number')},
        ),
        migrations.RemoveField(
            model_name='po',
            name='attainment',
        ),
        migrations.AddField(
            model_name='batch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='co',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='co',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='co',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='copomapping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='copomapping',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='copsomapping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='copsomapping',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='po',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='po',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='po',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='program',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='program',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pso',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pso',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pso',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheme',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='program_id',
            field=models.ForeignKey(db_column='p_id', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='academics.program'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='scheme_id',
            field=models.ForeignKey(db_column='scheme_id', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='academics.scheme'),
        ),
        migrations.AlterField(
            model_name='co',
            name='course_id',
            field=models.ForeignKey(db_column='c_id', on_delete=django.db.models.deletion.PROTECT, related_name='cos', to='academics.course'),
        ),
        migrations.AlterField(
            model_name='copomapping',
            name='co_id',
            field=models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.PROTECT, related_name='po_mappings', to='academics.co'),
        ),
        migrations.AlterField(
            model_name='copomapping',
            name='po_id',
            field=models.ForeignKey(db_column='po_id', on_delete=django.db.models.deletion.PROTECT, related_name='co_mappings', to='academics.po'),
        ),
        migrations.AlterField(
            model_name='copomapping',
            name='weightage',
            field=models.IntegerField(blank=True, help_text='mapping weight 1/2/3', null=True),
        ),
        migrations.AlterField(
            model_name='copsomapping',
            name='co_id',
            field=models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.PROTECT, related_name='pso_mappings', to='academics.co'),
        ),
        migrations.AlterField(
            model_name='copsomapping',
            name='pso_id',
            field=models.ForeignKey(db_column='pso_id', on_delete=django.db.models.deletion.PROTECT, related_name='co_mappings', to='academics.pso'),
        ),
        migrations.AlterField(
            model_name='copsomapping',
            name='weightage',
            field=models.IntegerField(blank=True, help_text='mapping weight 1/2/3', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='program_id',
            field=models.ForeignKey(db_column='p_id', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.program'),
        ),
        migrations.AlterField(
            model_name='pso',
            name='program_id',
            field=models.ForeignKey(db_column='p_id', on_delete=django.db.models.deletion.PROTECT, related_name='psos', to='academics.program'),
        ),
        migrations.AlterUniqueTogether(
            name='copomapping',
            unique_together={('co_id', 'po_id')},
        ),
        migrations.AlterUniqueTogether(
            name='copsomapping',
            unique_together={('co_id', 'pso_id')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_code', 'program_id')},
        ),
        migrations.RemoveField(
            model_name='co',
            name='target',
        ),
    ]
