# Generated by Django 6.0 on 2026-03-24 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cotarget',
            name='set_by',
            field=models.ForeignKey(blank=True, db_column='set_by', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='batches',
            field=models.ManyToManyField(blank=True, related_name='courses', to='academics.batch'),
        ),
        migrations.AddField(
            model_name='cotarget',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, to='academics.course'),
        ),
        migrations.AddField(
            model_name='co',
            name='course_id',
            field=models.ForeignKey(db_column='c_id', on_delete=django.db.models.deletion.PROTECT, related_name='cos', to='academics.course'),
        ),
        migrations.AddField(
            model_name='copomapping',
            name='po_id',
            field=models.ForeignKey(db_column='po_id', on_delete=django.db.models.deletion.PROTECT, related_name='co_mappings', to='academics.po'),
        ),
        migrations.AddField(
            model_name='potarget',
            name='po_id',
            field=models.ForeignKey(db_column='po_id', on_delete=django.db.models.deletion.PROTECT, to='academics.po'),
        ),
        migrations.AddField(
            model_name='potarget',
            name='set_by',
            field=models.ForeignKey(blank=True, db_column='set_by', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='po',
            name='program_id',
            field=models.ForeignKey(blank=True, db_column='p_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos', to='academics.program'),
        ),
        migrations.AddField(
            model_name='peo',
            name='program_id',
            field=models.ForeignKey(db_column='p_id', on_delete=django.db.models.deletion.CASCADE, related_name='peos', to='academics.program'),
        ),
        migrations.AddField(
            model_name='course',
            name='program_id',
            field=models.ForeignKey(db_column='p_id', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.program'),
        ),
        migrations.AddField(
            model_name='programstatement',
            name='program_id',
            field=models.ForeignKey(db_column='p_id', on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='academics.program'),
        ),
        migrations.AddField(
            model_name='pso',
            name='program_id',
            field=models.ForeignKey(db_column='p_id', on_delete=django.db.models.deletion.PROTECT, related_name='psos', to='academics.program'),
        ),
        migrations.AddField(
            model_name='copsomapping',
            name='pso_id',
            field=models.ForeignKey(db_column='pso_id', on_delete=django.db.models.deletion.PROTECT, related_name='co_mappings', to='academics.pso'),
        ),
        migrations.AddField(
            model_name='psotarget',
            name='pso_id',
            field=models.ForeignKey(db_column='pso_id', on_delete=django.db.models.deletion.PROTECT, to='academics.pso'),
        ),
        migrations.AddField(
            model_name='psotarget',
            name='set_by',
            field=models.ForeignKey(blank=True, db_column='set_by', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='scheme_id',
            field=models.ForeignKey(blank=True, db_column='scheme_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.scheme'),
        ),
        migrations.AddField(
            model_name='batch',
            name='scheme_id',
            field=models.ForeignKey(db_column='scheme_id', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='academics.scheme'),
        ),
        migrations.AddField(
            model_name='academicsetup',
            name='scheme_id',
            field=models.ForeignKey(db_column='scheme_id', on_delete=django.db.models.deletion.CASCADE, to='academics.scheme'),
        ),
        migrations.AlterUniqueTogether(
            name='co',
            unique_together={('course_id', 'co_number')},
        ),
        migrations.AlterUniqueTogether(
            name='copomapping',
            unique_together={('co_id', 'po_id')},
        ),
        migrations.AlterUniqueTogether(
            name='potarget',
            unique_together={('po_id', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='pso',
            unique_together={('program_id', 'pso_number')},
        ),
        migrations.AlterUniqueTogether(
            name='copsomapping',
            unique_together={('co_id', 'pso_id')},
        ),
        migrations.AlterUniqueTogether(
            name='psotarget',
            unique_together={('pso_id', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_code', 'program_id', 'scheme_id')},
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('scheme_id', 'batch_year')},
        ),
    ]
