# Generated by Django 6.0 on 2026-03-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='batches',
            field=models.ManyToManyField(blank=True, related_name='courses', to='academics.batch'),
        ),
    ]
