# Generated by Django 6.0 on 2026-02-21 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotarget',
            name='co_id',
            field=models.ForeignKey(blank=True, db_column='co_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.co'),
        ),
    ]
