# Generated by Django 6.0 on 2026-01-10 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_cotarget_alter_co_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='scheme_id',
            field=models.ForeignKey(blank=True, db_column='scheme_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.scheme'),
        ),
    ]
