# Generated by Django 6.0 on 2026-01-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_course_scheme_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('program_id', 'batch_year')},
        ),
        migrations.AlterUniqueTogether(
            name='pso',
            unique_together={('program_id', 'pso_number')},
        ),
    ]
