# Generated by Django 6.0 on 2026-03-05 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_course_batches'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_code', 'program_id', 'scheme_id')},
        ),
    ]
