# Generated by Django 6.0 on 2026-02-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_cotarget_co_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsetup',
            name='curriculum_link',
            field=models.URLField(default='https://econtent.msbte.edu.in/curriculum_search/', max_length=500),
        ),
    ]
