# Generated by Django 6.0 on 2026-03-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_course_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='introduction_year',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
