# Generated by Django 6.0 on 2026-01-17 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CISNature',
            fields=[
                ('nature_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Direct / Indirect', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CIS Nature',
                'verbose_name_plural': 'CIS Natures',
            },
        ),
        migrations.CreateModel(
            name='CISType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(help_text='Internal / External / Co-curricular', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nature_id', models.ForeignKey(db_column='nature_id', on_delete=django.db.models.deletion.PROTECT, related_name='types', to='cis_master.cisnature')),
            ],
            options={
                'verbose_name': 'CIS Type',
                'verbose_name_plural': 'CIS Types',
                'unique_together': {('nature_id', 'type_name')},
            },
        ),
        migrations.CreateModel(
            name='CISTerm',
            fields=[
                ('term_id', models.AutoField(primary_key=True, serialize=False)),
                ('term_code', models.CharField(help_text='FA-TH / SA-PR / CES', max_length=50)),
                ('term_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_id', models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='cis_master.cistype')),
            ],
            options={
                'verbose_name': 'CIS Term',
                'verbose_name_plural': 'CIS Terms',
                'unique_together': {('type_id', 'term_code')},
            },
        ),
    ]
