# Generated by Django 6.0 on 2026-01-18 12:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cisnature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cisnature',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cisterm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cisterm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cistype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cistype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cisterm',
            name='type_id',
            field=models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='cis_master.cistype'),
        ),
        migrations.AlterField(
            model_name='cistype',
            name='nature_id',
            field=models.ForeignKey(db_column='nature_id', on_delete=django.db.models.deletion.PROTECT, related_name='types', to='cis_master.cisnature'),
        ),
        migrations.AlterUniqueTogether(
            name='cisterm',
            unique_together={('type_id', 'term_code')},
        ),
        migrations.AlterUniqueTogether(
            name='cistype',
            unique_together={('nature_id', 'type_name')},
        ),
    ]
