# Generated by Django 6.0 on 2026-03-08 17:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingPlanLecture',
            fields=[
                ('lecture_id', models.AutoField(primary_key=True, serialize=False)),
                ('lecture_no', models.IntegerField()),
                ('lecture_date', models.DateField()),
                ('unit_no', models.IntegerField()),
                ('topic_planned', models.TextField()),
                ('actual_topic', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('INCOMPLETE', 'Incomplete'), ('POSTPONED', 'Postponed to next lecture')], default='INCOMPLETE', max_length=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teaching Plan Lecture',
                'verbose_name_plural': 'Teaching Plan Lectures',
                'db_table': 'academics_teaching_plan_lecture',
            },
        ),
        migrations.CreateModel(
            name='TeachingPlan',
            fields=[
                ('teaching_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_id', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.PROTECT, to='academics.batch')),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, to='academics.course')),
                ('scheme_id', models.ForeignKey(db_column='scheme_id', on_delete=django.db.models.deletion.PROTECT, to='academics.scheme')),
            ],
            options={
                'verbose_name': 'Teaching Plan',
                'verbose_name_plural': 'Teaching Plans',
                'db_table': 'academics_teaching_plan',
            },
        ),
    ]
