# Generated by Django 6.0 on 2026-01-14 12:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_batch_unique_together_and_more'),
        ('teaching_plan', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingplan',
            name='batch_id',
            field=models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.PROTECT, to='academics.batch'),
        ),
        migrations.AlterField(
            model_name='teachingplan',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, to='academics.course'),
        ),
        migrations.AlterField(
            model_name='teachingplan',
            name='scheme_id',
            field=models.ForeignKey(db_column='scheme_id', on_delete=django.db.models.deletion.PROTECT, to='academics.scheme'),
        ),
        migrations.AlterField(
            model_name='teachingplan',
            name='semester',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='teachingplan',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
        migrations.AlterField(
            model_name='teachingplanlecture',
            name='co_id',
            field=models.ForeignKey(blank=True, db_column='co_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.co'),
        ),
        migrations.AlterField(
            model_name='teachingplanlecture',
            name='teaching_plan_id',
            field=models.ForeignKey(db_column='teaching_plan_id', on_delete=django.db.models.deletion.PROTECT, related_name='lectures', to='teaching_plan.teachingplan'),
        ),
        migrations.AddConstraint(
            model_name='teachingplanlecture',
            constraint=models.UniqueConstraint(fields=('teaching_plan_id', 'lecture_no'), name='unique_lecture_no_per_teaching_plan'),
        ),
    ]
