# Generated by Django 6.0 on 2026-02-21 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('teaching_plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingplan',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teachingplanlecture',
            name='co_id',
            field=models.ForeignKey(blank=True, db_column='co_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.co'),
        ),
        migrations.AddField(
            model_name='teachingplanlecture',
            name='teaching_plan_id',
            field=models.ForeignKey(db_column='teaching_plan_id', on_delete=django.db.models.deletion.PROTECT, related_name='lectures', to='teaching_plan.teachingplan'),
        ),
        migrations.AddConstraint(
            model_name='teachingplanlecture',
            constraint=models.UniqueConstraint(fields=('teaching_plan_id', 'lecture_no'), name='unique_lecture_no_per_teaching_plan'),
        ),
    ]
