# Generated by Django 4.2.11 on 2026-04-14 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teaching_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingplan',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='teachingplanlecture',
            constraint=models.UniqueConstraint(fields=('teaching_plan_id', 'lecture_no'), name='unique_lecture_no_per_teaching_plan'),
        ),
    ]
