# Generated by Django 6.0 on 2026-03-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_plan', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingplanlecture',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('INCOMPLETE', 'Incomplete'), ('POSTPONED', 'Postponed to next lecture')], default='INCOMPLETE', max_length=20),
        ),
    ]
