# Generated by Django 4.2.11 on 2026-04-14 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSOBatchAttainment',
            fields=[
                ('attainment_id', models.AutoField(primary_key=True, serialize=False)),
                ('direct_value', models.FloatField(default=0.0)),
                ('indirect_value', models.FloatField(default=0.0)),
                ('normalized_value', models.FloatField()),
                ('gap', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_id', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.PROTECT, related_name='pso_attainments', to='academics.batch')),
                ('pso_id', models.ForeignKey(db_column='pso_id', on_delete=django.db.models.deletion.PROTECT, related_name='batch_attainments', to='academics.pso')),
            ],
            options={
                'verbose_name': 'PSO Batch Attainment',
                'verbose_name_plural': 'PSO Batch Attainments',
                'db_table': 'attainment_psobatchattainment',
                'unique_together': {('pso_id', 'batch_id')},
            },
        ),
        migrations.CreateModel(
            name='PSOAttainment',
            fields=[
                ('attainment_id', models.AutoField(primary_key=True, serialize=False)),
                ('pso_value', models.FloatField(help_text='Raw PSO value')),
                ('normalized_value', models.FloatField()),
                ('gap', models.FloatField(blank=True, help_text='Target - Normalized', null=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, related_name='pso_attainments', to='academics.course')),
                ('pso_id', models.ForeignKey(db_column='pso_id', on_delete=django.db.models.deletion.PROTECT, related_name='attainments', to='academics.pso')),
            ],
            options={
                'verbose_name': 'PSO Attainment',
                'verbose_name_plural': 'PSO Attainments',
                'db_table': 'attainment_psoattainment',
                'unique_together': {('pso_id', 'course_id', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='POBatchAttainment',
            fields=[
                ('attainment_id', models.AutoField(primary_key=True, serialize=False)),
                ('direct_value', models.FloatField(default=0.0)),
                ('indirect_value', models.FloatField(default=0.0)),
                ('normalized_value', models.FloatField()),
                ('gap', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_id', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.PROTECT, related_name='po_attainments', to='academics.batch')),
                ('po_id', models.ForeignKey(db_column='po_id', on_delete=django.db.models.deletion.PROTECT, related_name='batch_attainments', to='academics.po')),
            ],
            options={
                'verbose_name': 'PO Batch Attainment',
                'verbose_name_plural': 'PO Batch Attainments',
                'db_table': 'attainment_pobatchattainment',
                'unique_together': {('po_id', 'batch_id')},
            },
        ),
        migrations.CreateModel(
            name='POAttainment',
            fields=[
                ('attainment_id', models.AutoField(primary_key=True, serialize=False)),
                ('po_value', models.FloatField(help_text='Raw PO value')),
                ('normalized_value', models.FloatField()),
                ('gap', models.FloatField(blank=True, help_text='Target - Normalized', null=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, related_name='po_attainments', to='academics.course')),
                ('po_id', models.ForeignKey(db_column='po_id', on_delete=django.db.models.deletion.PROTECT, related_name='attainments', to='academics.po')),
            ],
            options={
                'verbose_name': 'PO Attainment',
                'verbose_name_plural': 'PO Attainments',
                'db_table': 'attainment_poattainment',
                'unique_together': {('po_id', 'course_id', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='CourseATR',
            fields=[
                ('atr_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=9)),
                ('action_proposed', models.TextField(help_text='Consolidated Action Taken/Proposed Report for the whole course')),
                ('atr_status', models.CharField(default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='course_atrs', to='academics.course')),
            ],
            options={
                'db_table': 'attainment_courseatr',
                'unique_together': {('course_id', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='COAttainment',
            fields=[
                ('attainment_id', models.AutoField(primary_key=True, serialize=False)),
                ('direct_attainment', models.FloatField()),
                ('indirect_attainment', models.FloatField(blank=True, null=True)),
                ('overall_attainment', models.FloatField(help_text='Weighted CO attainment (0.8L + 0.2M)')),
                ('gap', models.FloatField(help_text='Target vs achieved')),
                ('attainment_level', models.FloatField(help_text='Level 0.00 to 3.00')),
                ('academic_year', models.CharField(help_text='Academic year (e.g., 2024-25)', max_length=9)),
                ('atr_status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('not_required', 'Not Required')], default='not_required', max_length=20)),
                ('action_proposed', models.TextField(blank=True, help_text='Action Taken/Proposed Report (ATR)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('co_id', models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.PROTECT, related_name='attainments', to='academics.co')),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, related_name='co_attainments', to='academics.course')),
            ],
            options={
                'verbose_name': 'CO Attainment',
                'verbose_name_plural': 'CO Attainments',
                'db_table': 'attainment_coattainment',
                'unique_together': {('co_id', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Backtracking',
            fields=[
                ('backtracking_id', models.AutoField(primary_key=True, serialize=False)),
                ('direct_attainment', models.FloatField()),
                ('indirect_attainment', models.FloatField()),
                ('co_po_weightage', models.FloatField(help_text='CO -> PO mapping weight (1/2/3)')),
                ('final_po_contribution', models.FloatField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('co_id', models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.PROTECT, related_name='backtracking_entries', to='academics.co')),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, related_name='backtracking_entries', to='academics.course')),
                ('po_id', models.ForeignKey(db_column='po_id', on_delete=django.db.models.deletion.PROTECT, related_name='backtracking_entries', to='academics.po')),
            ],
            options={
                'verbose_name': 'Backtracking',
                'verbose_name_plural': 'Backtracking Entries',
                'db_table': 'backtracking',
                'unique_together': {('course_id', 'co_id', 'po_id', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='AttainmentSnapshot',
            fields=[
                ('snapshot_id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.PositiveSmallIntegerField(help_text='Month (1-12)')),
                ('year', models.PositiveSmallIntegerField(help_text='Academic year')),
                ('attainment_value', models.FloatField()),
                ('calculation_type', models.CharField(choices=[('monthly', 'Monthly'), ('cumulative', 'Cumulative')], max_length=15)),
                ('source', models.CharField(choices=[('direct', 'Direct'), ('indirect', 'Indirect'), ('combined', 'Combined')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('co_id', models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.PROTECT, related_name='attainment_snapshots', to='academics.co')),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, related_name='attainment_snapshots', to='academics.course')),
                ('po_id', models.ForeignKey(blank=True, db_column='po_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attainment_snapshots', to='academics.po')),
                ('pso_id', models.ForeignKey(blank=True, db_column='pso_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attainment_snapshots', to='academics.pso')),
            ],
            options={
                'verbose_name': 'Attainment Snapshot',
                'verbose_name_plural': 'Attainment Snapshots',
                'db_table': 'attainment_snapshot',
                'unique_together': {('month', 'year', 'course_id', 'co_id', 'po_id', 'pso_id', 'calculation_type', 'source')},
            },
        ),
    ]
