# Generated by Django 6.0 on 2026-03-12 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('attainment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poattainment',
            name='course_id',
            field=models.ForeignKey(blank=True, db_column='course_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_attainments', to='academics.course'),
        ),
        migrations.AlterField(
            model_name='psoattainment',
            name='course_id',
            field=models.ForeignKey(blank=True, db_column='course_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pso_attainments', to='academics.course'),
        ),
    ]
