# Generated by Django 6.0 on 2026-01-13 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_batch_unique_together_and_more'),
        ('attainment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attainmentsnapshot',
            name='co_id',
            field=models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.PROTECT, related_name='attainment_snapshots', to='academics.co'),
        ),
        migrations.AlterField(
            model_name='attainmentsnapshot',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, related_name='attainment_snapshots', to='academics.course'),
        ),
        migrations.AlterField(
            model_name='attainmentsnapshot',
            name='po_id',
            field=models.ForeignKey(blank=True, db_column='po_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attainment_snapshots', to='academics.po'),
        ),
        migrations.AlterField(
            model_name='attainmentsnapshot',
            name='pso_id',
            field=models.ForeignKey(blank=True, db_column='pso_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attainment_snapshots', to='academics.pso'),
        ),
        migrations.AlterField(
            model_name='backtracking',
            name='co_id',
            field=models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.PROTECT, related_name='backtracking_entries', to='academics.co'),
        ),
        migrations.AlterField(
            model_name='backtracking',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, related_name='backtracking_entries', to='academics.course'),
        ),
        migrations.AlterField(
            model_name='backtracking',
            name='po_id',
            field=models.ForeignKey(db_column='po_id', on_delete=django.db.models.deletion.PROTECT, related_name='backtracking_entries', to='academics.po'),
        ),
        migrations.AlterField(
            model_name='coattainment',
            name='co_id',
            field=models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.PROTECT, related_name='attainments', to='academics.co'),
        ),
        migrations.AlterField(
            model_name='coattainment',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, related_name='co_attainments', to='academics.course'),
        ),
        migrations.AlterField(
            model_name='poattainment',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, related_name='po_attainments', to='academics.course'),
        ),
        migrations.AlterField(
            model_name='poattainment',
            name='po_id',
            field=models.ForeignKey(db_column='po_id', on_delete=django.db.models.deletion.PROTECT, related_name='attainments', to='academics.po'),
        ),
        migrations.AlterUniqueTogether(
            name='attainmentsnapshot',
            unique_together={('month', 'year', 'course_id', 'co_id', 'po_id', 'pso_id', 'calculation_type', 'source')},
        ),
        migrations.AlterUniqueTogether(
            name='backtracking',
            unique_together={('course_id', 'co_id', 'po_id', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='coattainment',
            unique_together={('co_id', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='poattainment',
            unique_together={('po_id', 'academic_year')},
        ),
    ]
