# Generated by Django 6.0 on 2026-03-09 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('attainment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseATR',
            fields=[
                ('atr_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=9)),
                ('action_proposed', models.TextField(help_text='Consolidated Action Taken/Proposed Report for the whole course')),
                ('atr_status', models.CharField(default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='course_atrs', to='academics.course')),
            ],
            options={
                'db_table': 'attainment_courseatr',
                'unique_together': {('course_id', 'academic_year')},
            },
        ),
    ]
