# Generated by Django 6.0 on 2026-02-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attainment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coattainment',
            name='atr_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('not_required', 'Not Required')], default='not_required', max_length=20),
        ),
    ]
