# Generated by Django 6.0 on 2026-03-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attainment', '0002_alter_poattainment_course_id_and_more'),
        ('attainment', '0002_courseatr'),
    ]

    operations = [
    ]
