# Generated by Django 6.0 on 2026-03-22 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attainment', '0002_courseatr'),
    ]

    operations = [
    ]
