# Generated by Django 6.0 on 2026-03-22 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('attainment', '0003_batch_level_po_attainment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coattainment',
            name='attainment_level',
            field=models.FloatField(help_text='Level 0.00 to 3.00'),
        ),
        migrations.AlterUniqueTogether(
            name='poattainment',
            unique_together={('po_id', 'course_id', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='psoattainment',
            unique_together={('pso_id', 'course_id', 'academic_year')},
        ),
        migrations.CreateModel(
            name='POBatchAttainment',
            fields=[
                ('attainment_id', models.AutoField(primary_key=True, serialize=False)),
                ('direct_value', models.FloatField(default=0.0)),
                ('indirect_value', models.FloatField(default=0.0)),
                ('normalized_value', models.FloatField()),
                ('gap', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_id', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.PROTECT, related_name='po_attainments', to='academics.batch')),
                ('po_id', models.ForeignKey(db_column='po_id', on_delete=django.db.models.deletion.PROTECT, related_name='batch_attainments', to='academics.po')),
            ],
            options={
                'verbose_name': 'PO Batch Attainment',
                'verbose_name_plural': 'PO Batch Attainments',
                'db_table': 'attainment_pobatchattainment',
                'unique_together': {('po_id', 'batch_id')},
            },
        ),
        migrations.CreateModel(
            name='PSOBatchAttainment',
            fields=[
                ('attainment_id', models.AutoField(primary_key=True, serialize=False)),
                ('direct_value', models.FloatField(default=0.0)),
                ('indirect_value', models.FloatField(default=0.0)),
                ('normalized_value', models.FloatField()),
                ('gap', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_id', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.PROTECT, related_name='pso_attainments', to='academics.batch')),
                ('pso_id', models.ForeignKey(db_column='pso_id', on_delete=django.db.models.deletion.PROTECT, related_name='batch_attainments', to='academics.pso')),
            ],
            options={
                'verbose_name': 'PSO Batch Attainment',
                'verbose_name_plural': 'PSO Batch Attainments',
                'db_table': 'attainment_psobatchattainment',
                'unique_together': {('pso_id', 'batch_id')},
            },
        ),
    ]
