# Generated by Django 6.0 on 2026-03-23 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attainment', '0003_merge_20260316_1235'),
        ('attainment', '0004_alter_coattainment_attainment_level_and_more'),
    ]

    operations = [
    ]
