# Generated by Django 6.0 on 2026-03-23 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('attainment', '0005_merge_20260323_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poattainment',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='po_attainments', to='academics.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='psoattainment',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pso_attainments', to='academics.course'),
            preserve_default=False,
        ),
    ]
