# Generated by Django 6.0 on 2025-12-28 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='Academic Year', max_length=20)),
                ('report_file', models.FileField(help_text='PDF Report', upload_to='reports/')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', help_text='draft/approved/rejected', max_length=20)),
                ('auditor_remark', models.TextField(blank=True, help_text='Auditor comments', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Coordinator/HOD', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to='users.user')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='academics.course')),
                ('created_by', models.ForeignKey(help_text='Author', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to='users.user')),
            ],
        ),
    ]
