# Generated by Django 6.0 on 2025-12-31 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndirectAttainment',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('Co-curricular', 'Co-curricular'), ('Industrial Visit', 'Industrial Visit'), ('Extra-curricular', 'Extra-curricular')], max_length=50)),
                ('score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('co_id', models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.CASCADE, to='academics.co')),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
                ('student_id', models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
