# Generated by Django 6.0 on 2025-12-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indirect_attainment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indirectattainment',
            name='activity_type',
            field=models.CharField(choices=[('Co-curricular', 'Co-curricular'), ('Industrial Visit', 'Industrial Visit'), ('Extra-curricular', 'Extra-curricular')], max_length=50),
        ),
    ]
