# Generated by Django 4.2.11 on 2026-04-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_value', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Survey Answer',
                'verbose_name_plural': 'Survey Answers',
                'db_table': 'survey_answer',
            },
        ),
        migrations.CreateModel(
            name='SurveyMaster',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('survey_name', models.CharField(max_length=150)),
                ('survey_category', models.CharField(choices=[('feedback', 'Feedback'), ('course_exit', 'Course Exit'), ('indirect', 'Indirect')], max_length=30)),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('activity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_title', models.CharField(blank=True, max_length=200, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('conducted_date', models.DateField(blank=True, null=True)),
                ('resource_person_name', models.CharField(blank=True, max_length=200, null=True)),
                ('resource_person_designation', models.CharField(blank=True, max_length=200, null=True)),
                ('resource_person_company', models.CharField(blank=True, max_length=200, null=True)),
                ('resource_person_address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Survey Master',
                'verbose_name_plural': 'Survey Masters',
                'db_table': 'survey_master',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Survey Question',
                'verbose_name_plural': 'Survey Questions',
                'db_table': 'survey_question',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('respondent_name', models.CharField(blank=True, max_length=200, null=True)),
                ('enrollment_no', models.CharField(blank=True, max_length=20, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Survey Response',
                'verbose_name_plural': 'Survey Responses',
                'db_table': 'survey_response',
            },
        ),
    ]
