# Generated by Django 6.0 on 2026-01-17 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyMaster',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('survey_name', models.CharField(max_length=150)),
                ('survey_category', models.CharField(choices=[('feedback', 'Feedback'), ('course_exit', 'Course Exit'), ('indirect', 'Indirect')], max_length=30)),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('course_id', models.ForeignKey(blank=True, db_column='course_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.course')),
            ],
            options={
                'verbose_name': 'Survey Master',
                'verbose_name_plural': 'Survey Masters',
                'db_table': 'survey_master',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('co_id', models.ForeignKey(blank=True, db_column='co_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.co')),
                ('po_id', models.ForeignKey(blank=True, db_column='po_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.po')),
                ('survey_id', models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='surveys.surveymaster')),
            ],
            options={
                'verbose_name': 'Survey Question',
                'verbose_name_plural': 'Survey Questions',
                'db_table': 'survey_question',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('response_value', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question_id', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='surveys.surveyquestion')),
                ('student_id', models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.student')),
                ('survey_id', models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='surveys.surveymaster')),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'verbose_name': 'Survey Response',
                'verbose_name_plural': 'Survey Responses',
                'db_table': 'survey_response',
            },
        ),
    ]
