# Generated by Django 6.0 on 2026-01-14 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='survey_id',
            field=models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='surveys.surveymaster'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='question_id',
            field=models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='surveys.surveyquestion'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='survey_id',
            field=models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='surveys.surveymaster'),
        ),
    ]
