# Generated by Django 4.2.11 on 2026-04-14 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='student_id',
            field=models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.student'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='survey_id',
            field=models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='surveys.surveymaster'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='co_id',
            field=models.ForeignKey(blank=True, db_column='co_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.co'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='po_id',
            field=models.ForeignKey(blank=True, db_column='po_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.po'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='pso_id',
            field=models.ForeignKey(blank=True, db_column='pso_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.pso'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='survey_id',
            field=models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='surveys.surveymaster'),
        ),
        migrations.AddField(
            model_name='surveymaster',
            name='course_id',
            field=models.ForeignKey(blank=True, db_column='course_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.course'),
        ),
        migrations.AddField(
            model_name='surveymaster',
            name='program_id',
            field=models.ForeignKey(blank=True, db_column='program_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.program'),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='question_id',
            field=models.ForeignKey(blank=True, db_column='question_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='surveys.surveyquestion'),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='response_id',
            field=models.ForeignKey(db_column='response_id', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyresponse'),
        ),
    ]
