# Generated by Django 6.0 on 2026-02-27 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='student_id',
            field=models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.student'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='survey_id',
            field=models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='surveys.surveymaster'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='response_id',
            field=models.ForeignKey(db_column='response_id', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyresponse'),
        ),
    ]
