# Generated by Django 6.0 on 2026-02-25 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_cotarget_co_id'),
        ('surveys', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveymaster',
            name='activity_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='surveymaster',
            name='activity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='surveymaster',
            name='program_id',
            field=models.ForeignKey(blank=True, db_column='program_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.program'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='respondent_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
