# Generated by Django 6.0 on 2026-02-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_surveymaster_activity_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='enrollment_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
