# Generated by Django 6.0 on 2026-02-25 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_cotarget_co_id'),
        ('surveys', '0004_surveyresponse_enrollment_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='pso_id',
            field=models.ForeignKey(blank=True, db_column='pso_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.pso'),
        ),
    ]
