# Generated by Django 6.0 on 2026-02-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_surveyquestion_pso_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveymaster',
            name='conducted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveymaster',
            name='resource_person_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveymaster',
            name='resource_person_company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='surveymaster',
            name='resource_person_designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='surveymaster',
            name='resource_person_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
