# Generated by Django 6.0.1 on 2026-01-11 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=100)),
                ('entity_id', models.IntegerField()),
                ('action', models.CharField(choices=[('SUBMIT', 'Submit'), ('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(db_column='performed_by', on_delete=django.db.models.deletion.PROTECT, to='users.user')),
                ('role_id', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, to='users.userrole')),
            ],
            options={
                'db_table': 'audit_approval_action',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=100)),
                ('entity_id', models.IntegerField()),
                ('action', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(db_column='performed_by', on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'db_table': 'audit_log',
            },
        ),
    ]
