# Generated by Django 6.0 on 2025-12-31 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PO',
            fields=[
                ('po_id', models.AutoField(primary_key=True, serialize=False)),
                ('po_number', models.CharField(help_text='po1/po2/po3 etc', max_length=20)),
                ('description', models.TextField()),
                ('attainment', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Program Outcome',
                'verbose_name_plural': 'Program Outcomes',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('scheme_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheme_name', models.CharField(max_length=100)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CO',
            fields=[
                ('co_id', models.AutoField(primary_key=True, serialize=False)),
                ('co_number', models.CharField(help_text='co1/co2/co3 etc', max_length=20)),
                ('description', models.TextField()),
                ('target', models.FloatField(help_text='Target attainment level')),
                ('course_id', models.ForeignKey(db_column='c_id', on_delete=django.db.models.deletion.CASCADE, related_name='cos', to='academics.course')),
            ],
            options={
                'verbose_name': 'Course Outcome',
                'verbose_name_plural': 'Course Outcomes',
            },
        ),
        migrations.CreateModel(
            name='COPOMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('weightage', models.FloatField(help_text='mapping weight 1/2/3')),
                ('co_id', models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.CASCADE, related_name='po_mappings', to='academics.co')),
                ('po_id', models.ForeignKey(db_column='po_id', on_delete=django.db.models.deletion.CASCADE, related_name='co_mappings', to='academics.po')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='program_id',
            field=models.ForeignKey(db_column='p_id', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.program'),
        ),
        migrations.CreateModel(
            name='PSO',
            fields=[
                ('pso_id', models.AutoField(primary_key=True, serialize=False)),
                ('pso_number', models.CharField(help_text='pso1/pso2', max_length=20)),
                ('description', models.TextField()),
                ('program_id', models.ForeignKey(db_column='p_id', on_delete=django.db.models.deletion.CASCADE, related_name='psos', to='academics.program')),
            ],
            options={
                'verbose_name': 'Program Specific Outcome',
                'verbose_name_plural': 'Program Specific Outcomes',
            },
        ),
        migrations.CreateModel(
            name='COPSOMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('weightage', models.FloatField(help_text='mapping weight 1/2/3')),
                ('co_id', models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.CASCADE, related_name='pso_mappings', to='academics.co')),
                ('pso_id', models.ForeignKey(db_column='pso_id', on_delete=django.db.models.deletion.CASCADE, related_name='co_mappings', to='academics.pso')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_year', models.IntegerField(help_text='Year of admission')),
                ('program_id', models.ForeignKey(db_column='p_id', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='academics.program')),
                ('scheme_id', models.ForeignKey(db_column='scheme_id', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='academics.scheme')),
            ],
            options={
                'verbose_name_plural': 'Batches',
            },
        ),
    ]
