# Generated by Django 6.0.1 on 2026-01-11 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_year', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'db_table': 'academics_batch',
            },
        ),
        migrations.CreateModel(
            name='CO',
            fields=[
                ('co_id', models.AutoField(primary_key=True, serialize=False)),
                ('co_number', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'academics_co',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=150)),
                ('semester', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'academics_course',
            },
        ),
        migrations.CreateModel(
            name='PO',
            fields=[
                ('po_id', models.AutoField(primary_key=True, serialize=False)),
                ('po_number', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'academics_po',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=100)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'academics_program',
            },
        ),
        migrations.CreateModel(
            name='PSO',
            fields=[
                ('pso_id', models.AutoField(primary_key=True, serialize=False)),
                ('pso_number', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'academics_pso',
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('scheme_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheme_name', models.CharField(max_length=50)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'academics_scheme',
            },
        ),
        migrations.CreateModel(
            name='COPOMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('weightage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('co_id', models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.CASCADE, to='academics.co')),
            ],
            options={
                'db_table': 'academics_copo_mapping',
            },
        ),
        migrations.CreateModel(
            name='COPSOMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('weightage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('co_id', models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.CASCADE, to='academics.co')),
            ],
            options={
                'db_table': 'academics_copso_mapping',
            },
        ),
        migrations.CreateModel(
            name='COTarget',
            fields=[
                ('target_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=9)),
                ('target_value', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_id', models.ForeignKey(blank=True, db_column='batch_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.batch')),
                ('co_id', models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.PROTECT, to='academics.co')),
            ],
            options={
                'db_table': 'co_target',
            },
        ),
    ]
