# Generated by Django 6.0.1 on 2026-01-11 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotarget',
            name='set_by',
            field=models.ForeignKey(db_column='set_by', on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
        migrations.AddField(
            model_name='co',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, to='academics.course'),
        ),
        migrations.AddField(
            model_name='copomapping',
            name='po_id',
            field=models.ForeignKey(db_column='po_id', on_delete=django.db.models.deletion.CASCADE, to='academics.po'),
        ),
        migrations.AddField(
            model_name='po',
            name='program_id',
            field=models.ForeignKey(db_column='program_id', on_delete=django.db.models.deletion.PROTECT, to='academics.program'),
        ),
        migrations.AddField(
            model_name='course',
            name='program_id',
            field=models.ForeignKey(db_column='program_id', on_delete=django.db.models.deletion.PROTECT, to='academics.program'),
        ),
        migrations.AddField(
            model_name='batch',
            name='program_id',
            field=models.ForeignKey(db_column='program_id', on_delete=django.db.models.deletion.PROTECT, to='academics.program'),
        ),
        migrations.AddField(
            model_name='pso',
            name='program_id',
            field=models.ForeignKey(db_column='program_id', on_delete=django.db.models.deletion.PROTECT, to='academics.program'),
        ),
        migrations.AddField(
            model_name='copsomapping',
            name='pso_id',
            field=models.ForeignKey(db_column='pso_id', on_delete=django.db.models.deletion.CASCADE, to='academics.pso'),
        ),
        migrations.AddField(
            model_name='course',
            name='scheme_id',
            field=models.ForeignKey(db_column='scheme_id', on_delete=django.db.models.deletion.PROTECT, to='academics.scheme'),
        ),
        migrations.AddField(
            model_name='batch',
            name='scheme_id',
            field=models.ForeignKey(db_column='scheme_id', on_delete=django.db.models.deletion.PROTECT, to='academics.scheme'),
        ),
        migrations.AlterUniqueTogether(
            name='cotarget',
            unique_together={('co_id', 'academic_year', 'batch_id')},
        ),
        migrations.AlterUniqueTogether(
            name='co',
            unique_together={('course_id', 'co_number')},
        ),
        migrations.AlterUniqueTogether(
            name='copomapping',
            unique_together={('co_id', 'po_id')},
        ),
        migrations.AlterUniqueTogether(
            name='po',
            unique_together={('program_id', 'po_number')},
        ),
        migrations.AlterUniqueTogether(
            name='pso',
            unique_together={('program_id', 'pso_number')},
        ),
        migrations.AlterUniqueTogether(
            name='copsomapping',
            unique_together={('co_id', 'pso_id')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_code', 'scheme_id')},
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('batch_year', 'program_id')},
        ),
    ]
