# Generated by Django 6.0.1 on 2026-01-11 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttainmentSnapshot',
            fields=[
                ('snapshot_id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.CharField(max_length=9)),
                ('attainment_value', models.FloatField()),
                ('calculation_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('co_id', models.ForeignKey(blank=True, db_column='co_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.co')),
                ('course_id', models.ForeignKey(blank=True, db_column='course_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.course')),
                ('po_id', models.ForeignKey(blank=True, db_column='po_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.po')),
                ('pso_id', models.ForeignKey(blank=True, db_column='pso_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.pso')),
                ('verified_by', models.ForeignKey(db_column='verified_by', on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'db_table': 'attainment_snapshot',
            },
        ),
        migrations.CreateModel(
            name='COAttainment',
            fields=[
                ('attainment_id', models.AutoField(primary_key=True, serialize=False)),
                ('direct_attainment', models.FloatField()),
                ('indirect_attainment', models.FloatField()),
                ('overall_attainment', models.FloatField()),
                ('gap', models.FloatField()),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('co_id', models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.PROTECT, to='academics.co')),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, to='academics.course')),
            ],
            options={
                'db_table': 'attainment_co_attainment',
            },
        ),
        migrations.CreateModel(
            name='COPOMappingAttainment',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('direct_attainment', models.FloatField()),
                ('indirect_attainment', models.FloatField()),
                ('co_po_weightage', models.FloatField()),
                ('final_po_contribution', models.FloatField()),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('co_id', models.ForeignKey(db_column='co_id', on_delete=django.db.models.deletion.PROTECT, to='academics.co')),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, to='academics.course')),
                ('po_id', models.ForeignKey(db_column='po_id', on_delete=django.db.models.deletion.PROTECT, to='academics.po')),
            ],
            options={
                'db_table': 'attainment_co_po_mapping',
            },
        ),
        migrations.CreateModel(
            name='CourseAttainment',
            fields=[
                ('attainment_id', models.AutoField(primary_key=True, serialize=False)),
                ('direct_attainment', models.FloatField()),
                ('indirect_attainment', models.FloatField()),
                ('overall_attainment', models.FloatField()),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, to='academics.course')),
            ],
            options={
                'db_table': 'attainment_course_attainment',
            },
        ),
    ]
