# Generated by Django 6.0 on 2025-12-29 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttainmentSnapshot',
            fields=[
                ('snapshot_id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.PositiveSmallIntegerField(help_text='Month (1-12)')),
                ('year', models.PositiveSmallIntegerField(help_text='Academic year')),
                ('attainment_value', models.FloatField()),
                ('calculation_type', models.CharField(choices=[('monthly', 'Monthly'), ('cumulative', 'Cumulative')], max_length=15)),
                ('source', models.CharField(choices=[('direct', 'Direct'), ('indirect', 'Indirect'), ('combined', 'Combined')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attainment_snapshots', to='academics.co')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attainment_snapshots', to='academics.course')),
                ('po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attainment_snapshots', to='academics.po')),
                ('pso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attainment_snapshots', to='academics.pso')),
            ],
            options={
                'verbose_name': 'Attainment Snapshot',
                'verbose_name_plural': 'Attainment Snapshots',
                'db_table': 'attainment_snapshot',
            },
        ),
        migrations.CreateModel(
            name='Backtracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direct_attainment', models.FloatField()),
                ('indirect_attainment', models.FloatField()),
                ('co_po_weightage', models.FloatField(help_text='CO -> PO mapping weight (1/2/3)')),
                ('final_po_contribution', models.FloatField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtracking_entries', to='academics.co')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtracking_entries', to='academics.course')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtracking_entries', to='academics.po')),
            ],
            options={
                'verbose_name': 'Backtracking',
                'verbose_name_plural': 'Backtracking Entries',
                'db_table': 'backtracking',
            },
        ),
        migrations.CreateModel(
            name='COAttainment',
            fields=[
                ('attainment_id', models.AutoField(primary_key=True, serialize=False)),
                ('direct_attainment', models.FloatField()),
                ('indirect_attainment', models.FloatField(blank=True, null=True)),
                ('overall_attainment', models.FloatField(help_text='Weighted CO attainment (0.8L + 0.2M)')),
                ('gap', models.FloatField(help_text='Target vs achieved')),
                ('attainment_level', models.IntegerField(help_text='Level 1/2/3')),
                ('academic_year', models.CharField(help_text='Academic year (e.g., 2024-25)', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attainments', to='academics.co')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_attainments', to='academics.course')),
            ],
            options={
                'verbose_name': 'CO Attainment',
                'verbose_name_plural': 'CO Attainments',
                'db_table': 'attainment_coattainment',
            },
        ),
        migrations.CreateModel(
            name='POAttainment',
            fields=[
                ('attainment_id', models.AutoField(primary_key=True, serialize=False)),
                ('po_value', models.FloatField(help_text='Raw PO value')),
                ('normalized_value', models.FloatField()),
                ('academic_year', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_attainments', to='academics.course')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attainments', to='academics.po')),
            ],
            options={
                'verbose_name': 'PO Attainment',
                'verbose_name_plural': 'PO Attainments',
                'db_table': 'attainment_poattainment',
            },
        ),
    ]
