# Generated by Django 6.0 on 2026-01-17 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DISABLE', 'DISABLE'), ('APPROVE', 'APPROVE'), ('VERIFY', 'VERIFY'), ('CALCULATE', 'CALCULATE'), ('LOCK', 'LOCK'), ('UNLOCK', 'UNLOCK')], max_length=30)),
                ('entity_name', models.CharField(max_length=100)),
                ('entity_id', models.IntegerField()),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role_id', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, to='users.userrole')),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'db_table': 'audit_log',
            },
        ),
    ]
