# Generated by Django 4.2.11 on 2026-04-14 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='role_id',
            field=models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userrole'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
