# Generated by Django 6.0.1 on 2026-01-11 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CISNature',
            fields=[
                ('nature_id', models.AutoField(primary_key=True, serialize=False)),
                ('nature_name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cis_nature',
            },
        ),
        migrations.CreateModel(
            name='CISType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('nature_id', models.ForeignKey(db_column='nature_id', on_delete=django.db.models.deletion.CASCADE, to='cis_master.cisnature')),
            ],
            options={
                'db_table': 'cis_type',
            },
        ),
        migrations.CreateModel(
            name='CISTerm',
            fields=[
                ('term_id', models.AutoField(primary_key=True, serialize=False)),
                ('term_name', models.CharField(max_length=100)),
                ('weightage', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('type_id', models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.CASCADE, to='cis_master.cistype')),
            ],
            options={
                'db_table': 'cis_term',
            },
        ),
    ]
