# Generated by Django 6.0 on 2025-12-29 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CISNature',
            fields=[
                ('nature_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Direct / Indirect', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CIS Nature',
                'verbose_name_plural': 'CIS Natures',
            },
        ),
        migrations.CreateModel(
            name='CISType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(help_text='Internal / External / Co-curricular', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='cis_master.cisnature')),
            ],
            options={
                'verbose_name': 'CIS Type',
                'verbose_name_plural': 'CIS Types',
            },
        ),
        migrations.CreateModel(
            name='CISTerm',
            fields=[
                ('term_id', models.AutoField(primary_key=True, serialize=False)),
                ('term_code', models.CharField(help_text='FA-TH / SA-PR / CES', max_length=50)),
                ('term_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='cis_master.cistype')),
            ],
            options={
                'verbose_name': 'CIS Term',
                'verbose_name_plural': 'CIS Terms',
            },
        ),
    ]
